### PR TITLE
componentWillReceiveProps deprecation warning

### PR DESCRIPTION
**Pull request by vidup**
I replaced it with componentDidUpdate in order to remove the deprecation warning.

### CODE REVIEW

**Comment by vidup** [comment]
Hey @antonfisher, I was just passing by and saw this issue. I hope you don't mind the unannounced pull request !

**Comment by antonfisher** [comment]
Thanks for that! I was trying to do similar fix, but I took me more than 2 hours, and I'm waiting for weekends to try again :)
I see two test cases were failed for this PR: https://travis-ci.org/antonfisher/react-simple-timefield/builds/590497887#L291
I'll verify them manually.
If you got any feedback on this, it's welcome!

**Comment by antonfisher** [comment]
I did some changes and released it: https://github.com/antonfisher/react-simple-timefield/releases/tag/v3.0.0

**Comment by vidup** [comment]
Cool, good job !

**Pull request closed without merging**
